### PR TITLE
Runtime fixes

### LINKED ISSUE #13: Various Runtime Bugs
Just so that I can keep track:
- [ ] inner field dimensions are actually larger than outer (I.e. including halo) dimensions
- [ ] Incorrect MPI rank usage: mpi rank is in [0:n-1], while the allocated subdomains array is [1:n]--> out of bound access
- [ ] field_mod.f90 tries to split a fields into tiles, one for each thread. But PSyclone does not create tiled loops. So either fix PSyclone to loop over 'tiles', or (preferred imho) don't create tiles for fields, just leave it as one field. Long term we might want to make this a user option: either one tile for each thread, or one tile for all threads, and then use OpenMP to distribute loops.

### PR DESCRIPTION
**Pull request by hiker**
Fixes #13.

### CODE REVIEW

File: finite_difference/src/argument_mod.f90 [hunk 1]
```diff
@@ -103,6 +103,11 @@ module argument_mod
 !> Kernel requires the vertical grid spacing of the grid.
 !! Requires/assumes that this quantity is constant.
 integer, public, parameter :: GO_GRID_DY_CONST = 15
+integer, public, parameter :: GO_GRID_X_MIN_INDEX=16
```
Comment (arporter) [inline finite_difference/src/argument_mod.f90:109]: Please add comments specifying what these quantities are - i.e. do they refer to the internal region, the whole grid or something else?

File: finite_difference/src/field_mod.f90 [hunk 2]
```diff
@@ -187,7 +198,10 @@ function r2d_field_constructor(grid,    &
        ntiley = 1
     end if
     nthreads = 1
-!$  nthreads = omp_get_max_threads()
+    if (present(do_tile) .and. do_tile) then
```
Comment (arporter) [inline finite_difference/src/field_mod.f90]: I got caught out by this recently - Fortran does not do lazy evaluation so you can't assume that the `present(do_tile)` will happen before the reference to `do_tile`. It's a pain but you have to have two, separate `if` statements. (I was getting away with it until I tried the PGI compiler.)

File: finite_difference/src/subdomain_mod.f90 [hunk 3]
```diff
@@ -162,7 +162,8 @@ function decompose(domainx, domainy,             &
     end if
 
     decomp%ndomains = ndom
-    allocate(decomp%subdomains(ndom), Stat=ierr)
+    ! Ranks start with 0, so allocate the subdomains starting with 0
```
Comment (arporter) [inline finite_difference/src/subdomain_mod.f90]: Is there a reason for this change? In my other work (#7) I've been working on the principle that, since this is Fortran, we'll add one to the MPI rank. I can go either way :-)

**Review by arporter — CHANGES_REQUESTED** [review]
Many thanks for these improvements. There's one coding error (see inline) and we need to jointly decide whether we zero-index the subdomains array or not.

File: finite_difference/src/field_mod.f90 (hunk 2 above)
Comment (hiker) [reply finite_difference/src/field_mod.f90]: Gee, 30+years of Fortran programming, and I didn't know - embarrassing. I guess this kind of construct is more common in C++ ;)

File: finite_difference/src/argument_mod.f90 (hunk 1 above)
Comment (hiker) [reply finite_difference/src/argument_mod.f90:109]: Done, but there is a bit of an issue: the constants being declared in dl_esm_inf, while their usage is specified in PSyclone. This should (imho) go into a config file ... in the distant future I guess ;)

File: finite_difference/src/subdomain_mod.f90 (hunk 3 above)
Comment (hiker) [reply finite_difference/src/subdomain_mod.f90]: Hmm - I changed it because I had a crash, but upon looking at it now I realised that was because I did not call parallel_init. So, I moved it all back to be based on 1-n . Though I can't help myself to point out that in a comment in #7 you write: 
```
subdomain[ 0]( 1: 20)( 1: 20), interior:( 2: 21)( 2: 21)
subdomain[ 1]( 1: 20)( 21: 40), interior:( 2: 21)( 2: 21)
```
which appears to be 0 based ;)

**Comment by hiker** [comment]
OK, ready to go.

File: finite_difference/src/subdomain_mod.f90 (hunk 3 above)
Comment (arporter) [reply finite_difference/src/subdomain_mod.f90]: Oh yes, so I did :-( I think, in my defence, that that is within the decomposition code. My plan is that publicly it will be 1-indexed. (I'll have to check what I've done and then you can review it :-) )

File: finite_difference/src/field_mod.f90 (hunk 2 above)
Comment (arporter) [reply finite_difference/src/field_mod.f90]: Don't worry - I only discovered this myself within the last month!

File: finite_difference/src/argument_mod.f90 (hunk 1 above)
Comment (arporter) [reply finite_difference/src/argument_mod.f90:109]: Ah yes, that's a good point. Definitely something for the future :-)

**Review by arporter — APPROVED** [review]

**Comment by arporter** [comment]
New version compiles. Example mini-app compiles and runs OK (both serial and DM parallel).
